### ISSUE TITLE
Suggestions on how to handle two different local versions of cli

### ISSUE THREAD

**Issue by mpamarques** [criticalmanufacturing/cli#109]
Hi,

If I am involved in two different projects that use different cli versions, what's your suggestion on how to handle it? v2 introduces breaking changes from v1, so when I install it locally it may affect the project that still depends on cli v1.

Thank you.

**Comment by m-s-** [comment]
Hi Miguel,
for local operations we kept the breaking changes to a minimum, so you should not see many issues when e.g. running a bump. Maybe there can be some problems with the tests package, due to the type rename. Try it and see what exact problems you have.

If you indeed need to run different versions, the CLI can also be installed locally. So in your project root you can install it with e.g. `npm i @criticalmanufacturing/cli --no-save` and the invoke it from `node_modules/.bin/cmf`. This is how we run concurrent versions in the build servers at CMF.

I'll close this now, but let me know if you need any more help.
